declare const RAW_SENTINELS: string[];
type MediaAsset = {
    id: string;
    mood: string;
    path: string;
    alt: string;
    state: string;
    sourceClass: string;
    license: string;
};
type CandidateOption = {
    id: string;
    title: string;
    mood: string;
    tone: string;
    media: MediaAsset;
    summary: string;
    evidence: string;
};
type PlanningApiField = {
    fieldId: string;
    label: string;
    primitiveId: string;
    rendererKey: string;
    value: string;
    isRequired: boolean;
    state: string;
    evidenceId?: string | null;
    allowedValues: string[];
};
type PlanningApiPrimitive = {
    instanceId: string;
    primitiveId: string;
    rendererKey: string;
    title: string;
    prompt: string;
    moodToken: string;
    mediaToken: string;
    state: string;
    fields: PlanningApiField[];
    candidates: CandidateOption[];
    evidenceIds: string[];
    errorCode?: string | null;
    blockedReason?: string | null;
};
type PlanningApiTurn = {
    turnId: string;
    sessionId: string;
    graphRevision: string;
    source: string;
    outcomeCode: string;
    manifestVersion: string;
    primitives: PlanningApiPrimitive[];
    providerRequestState: string;
    providerOutcome: string;
    rawAbsenceState: string;
};
type PlanningApiState = {
    modeState: string;
    selectedModelRole: string;
    selectedProvider: string;
    livePreflightState: string;
    liveProposalState: string;
    harnessValidationState: string;
    latestTurnSource: string;
    providerRequestState: string;
    providerOutcome: string;
    providerHealth: string;
    finalState: string;
    errorCode?: string | null;
    blockedReason?: string | null;
};
type PlanningApiResponse = {
    sessionId: string;
    status: string;
    state: PlanningApiState;
    turn?: PlanningApiTurn | null;
    rawAbsenceState: string;
};
declare const mediaAssets: Record<string, MediaAsset>;
declare function mediaAsset(assetId: string): MediaAsset;
declare const candidates: CandidateOption[];
declare const scenicCandidate: CandidateOption;
declare const fallbackCandidate: CandidateOption;
declare const calmMorningMedia: MediaAsset;
declare const restorativeDowntimeMedia: MediaAsset;
declare const FALLBACK_DELAY_MS = 350;
declare const CIRCUIT_HEALTH_DELAY_MS = 1500;
declare const HTTP_TRANSPORT_DELAY_MS = 1800;
declare let pendingHttpPlanning: boolean;
declare function sanitizeText(value: string): string;
declare function escapeHtml(value: string | null | undefined): string;
declare function root(): HTMLElement | null;
declare function transcript(): HTMLElement | null;
declare function chatMain(): HTMLElement | null;
declare function scheduleFallback(shouldRun: () => boolean, action: () => void): void;
declare function circuitUnavailable(): boolean;
declare function scheduleHttpTransport(shouldRun: () => boolean, action: () => Promise<void>): void;
declare function showDisconnectedState(): void;
declare function setRootState(attrs: Record<string, string>): void;
declare function selectedModelRole(): string;
declare function setModelRole(role: string): void;
declare function appendTurn(id: string, role: string, kind: string, state: string, text: string, outcome: string, evidence?: string, candidateId?: string): HTMLElement | null;
declare function startLivePlanningViaHttp(promptText?: string): Promise<void>;
declare function submitPrimitiveAnswerViaHttp(primitiveInstanceId: string): Promise<void>;
declare function applyPlanningApiResponse(response: PlanningApiResponse, transport: string): void;
declare function renderApiTurn(turn: PlanningApiTurn | null | undefined): void;
declare function formPrimitiveHtml(turn: PlanningApiTurn, primitive: PlanningApiPrimitive): string;
declare function primitiveMessageHtml(turn: PlanningApiTurn, primitive: PlanningApiPrimitive): string;
declare function candidateCard(candidate: (typeof candidates)[number], state?: string): string;
declare function timelineItem(id: string, mode: string, kind: string, state: string, title: string, summary: string, originTurnId: string, media: MediaAsset, attrs?: string): string;
declare function ensurePlanningTimeline(): void;
declare function ensureWorkObjects(): void;
declare function sendPrompt(): void;
declare function submitForm(): void;
declare function selectCandidate(candidateId: string): void;
declare function deferCandidate(candidateId: string): void;
declare function requestApproval(): void;
declare function setAskTabVisible(visible: boolean): void;
declare function toggleDrawer(open: boolean): void;
declare function moveDeck(direction: number): void;
declare function setTimelineMode(mode: string): void;
declare function focusOriginTurn(turnId: string): void;
declare function closestAction(target: EventTarget | null, selector: string): HTMLElement | null;
declare function closeDrawerAfterFocusLeaves(target: EventTarget | null): void;
declare function closeDrawerOnOutsidePointer(target: EventTarget | null): void;
declare const chatActionSelector: string;
declare function interceptChatAction(event: Event): void;
declare function handleChatInteraction(target: EventTarget | null): void;
declare function isReconnectBlocked(modal: HTMLDialogElement | null): boolean;
